package: rpc
version: '1.0.0'
author: Tim Filler
supportpage: https://redaxo.org
page:
  title: 'translate:rpc'
  perm: rpc[]
  pjax: false
  icon: rex-icon fa-print
  subpages:
    orders:
      title: 'translate:rpc_orders'
      icon: rex-icon fa-file
    configuration:
      title: 'translate:rpc_config'
      icon: rex-icon fa-cogs
    help:
      title: 'translate:rpc_help'
      icon: rex-icon fa-help
      eigener: default
requires:
  redaxo: '^5.6'
  packages:
    yform: '^3.0'